spring:
  datasource:
    username: postgres
    password: sasha2004
    url: jdbc:postgresql://localhost:5432/weather_db
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: demo

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG


app:
  cred: # в реальном мире всякие токены просто так в проперти не лежат, но возможности вынести их пока нет
    token: PASSWORDTOKENTOPSECRET

