spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
  application:
    name: demo

app:
  cred: # в реальном мире всякие токены просто так в проперти не лежат, но возможности вынести их пока нет
    token: PASSWORDTOKENTOPSECRET